import os
import boto3
from pathlib import Path

def upload_to_s3(bucket_name, source_path, s3_prefix=""):
    """Uploads a file or a whole directory to an S3 bucket."""
    s3 = boto3.client('s3')
    source_path = Path(source_path)
    
    if not source_path.exists():
        print(f"⚠️ Warning: '{source_path}' not found locally. Skipping.")
        return

    # If it's a single file (like our GGUF)
    if source_path.is_file():
        s3_key = os.path.join(s3_prefix, source_path.name).replace("\\", "/")
        print(f"Uploading {source_path.name} to s3://{bucket_name}/{s3_key}...")
        s3.upload_file(str(source_path), bucket_name, s3_key)
        
    # If it's a directory (like our LoRA adapter folder)
    else:
        print(f"Uploading directory {source_path.name}...")
        for root, _, files in os.walk(source_path):
            for file in files:
                local_path = os.path.join(root, file)
                relative_path = os.path.relpath(local_path, source_path)
                s3_key = os.path.join(s3_prefix, source_path.name, relative_path).replace("\\", "/")
                
                print(f"  -> Pushing {relative_path}...")
                s3.upload_file(local_path, bucket_name, s3_key)

if __name__ == "__main__":
    print("🚀 Forge MLOps: Artifact S3 Uploader")
    print("-" * 40)
    
    # Ask the user for the bucket name generated by Terraform
    bucket = input("Enter your S3 Bucket Name (from Terraform output): ").strip()
    
    if not bucket:
        print("❌ Error: Bucket name is required.")
        exit(1)
        
    print("\n📦 1/2 Uploading Base GGUF Model...")
    upload_to_s3(bucket, "legal_slm-unsloth.Q4_K_M.gguf", "models/base")
    
    print("\n📦 2/2 Uploading LoRA Adapters...")
    # Update this path if your adapter folder is named differently
    upload_to_s3(bucket, "models/legal_qlora_adapter", "models/adapters")
    
    print("\n✅ Phase 1 Complete! Your model artifacts are safely versioned in AWS.")