import json
import os
import base64
import boto3
import fitz  # PyMuPDF
from llama_cpp import Llama

# ------------------------------------------------------
# COLD START INITIALIZATION
# ------------------------------------------------------
S3_BUCKET = os.environ.get("MODEL_BUCKET", "forge-legal-slm-artifacts-c547855a")
MODEL_KEY = "models/base/legal_slm_custom_q3.gguf" 
LOCAL_MODEL_PATH = "/tmp/model.gguf"

s3_client = boto3.client('s3')

print("Initializing Serverless Inference Engine...")

if not os.path.exists(LOCAL_MODEL_PATH):
    print(f"Downloading model from s3://{S3_BUCKET}/{MODEL_KEY}...")
    s3_client.download_file(S3_BUCKET, MODEL_KEY, LOCAL_MODEL_PATH)
    print("Download complete.")

# FIX 1: Enforce explicit n_ctx to overwrite the 1024 baseline limit
llm = Llama(
    model_path=LOCAL_MODEL_PATH,
    n_ctx=4096,
    n_threads=4,
    verbose=False
)
print("Model loaded into memory successfully.")

# ------------------------------------------------------
# INFERENCE CONFIGURATION
# ------------------------------------------------------
PAGES_PER_CHUNK = 3
SYSTEM_PROMPT = "Extract structured legal metadata from text into a valid JSON object containing keys: 'parties' (array), 'effective_date' (string), 'liability_cap' (string), and 'termination_conditions' (string). Respond with raw JSON only."

def _build_response(status_code, body):
    return {
        "statusCode": status_code,
        "headers": {
            "Access-Control-Allow-Origin": "*",
            "Access-Control-Allow-Headers": "Content-Type",
            "Access-Control-Allow-Methods": "OPTIONS,POST",
            "Content-Type": "application/json"
        },
        "body": json.dumps(body) if isinstance(body, dict) else body
    }

# FIX 2: Correct structure to match target instruction format without double BOS tags
def build_prompt(text_chunk: str) -> str:
    return (
        "<|start_header_id|>system<|end_header_id|>\n\n"
        f"{SYSTEM_PROMPT}<|eot_id|>"
        "<|start_header_id|>user<|end_header_id|>\n\n"
        f"Document text:\n\"\"\"\n{text_chunk}\n\"\"\"<|eot_id|>"
        "<|start_header_id|>assistant<|end_header_id|>\n\n"
    )

def extract_json_from_chunk(text_chunk: str):
    prompt = build_prompt(text_chunk)
    try:
        # Lower temperature ensures high strictness for mechanical extraction
        response = llm(prompt, max_tokens=1024, stop=["<|eot_id|>"], temperature=0.1)
        output_text = response['choices'][0]['text'].strip()
        
        # Strip out code blocks markdown formatting wraps if generated by the LLM
        cleaned = output_text.replace("```json", "").replace("```", "").strip()
        return json.loads(cleaned)
    except Exception as e:
        print(f"Error parsing chunk JSON: {e}")
        return {}

def lambda_handler(event, context):
    print(f"REQUEST RECEIVED: {event.get('httpMethod')} {event.get('path')}")
    
    # 1. Health Check
    if event.get('httpMethod') == 'GET' or event.get('path') == '/health':
        return _build_response(200, {"status": "alive"})

    # 2. CORS Preflight
    if event.get('httpMethod') == 'OPTIONS':
        return _build_response(200, "OK")

    try:
        # 3. Decode payload body bytes
        body = event.get('body', '')
        is_base64 = event.get('isBase64Encoded', False)
        body_bytes = base64.b64decode(body) if is_base64 else body.encode('utf-8')
        
        # 4. Handle Multipart-Form data encapsulation or raw PDF data cleanly
        pdf_start = body_bytes.find(b'%PDF-')
        if pdf_start == -1:
            return _build_response(400, {"error": "No valid PDF header found."})
        
        pdf_end = body_bytes.rfind(b'%%EOF')
        if pdf_end != -1:
            pdf_clean_bytes = body_bytes[pdf_start:pdf_end + 5]
        else:
            pdf_clean_bytes = body_bytes[pdf_start:]

        # 5. Process PDF text streams
        doc = fitz.open(stream=pdf_clean_bytes, filetype="pdf")
        chunks = []
        current_chunk = ""
        
        for i in range(len(doc)):
            current_chunk += doc.load_page(i).get_text("text") + "\n\n"
            if (i + 1) % PAGES_PER_CHUNK == 0 or i == len(doc) - 1:
                chunks.append(current_chunk.strip())
                current_chunk = ""

        # 6. Serialized Execution & Aggregate Result Formatting
        chunk_results = [extract_json_from_chunk(c) for c in chunks]
        master_json = {
            "parties": [], 
            "effective_date": "Not Specified", 
            "liability_cap": "Not Specified", 
            "termination_conditions": "Not Specified"
        }
        
        for result in chunk_results:
            if not isinstance(result, dict):
                continue
            
            # Map elements cleanly into aggregated structure
            for party in result.get("parties", []):
                if party not in master_json["parties"] and party != "Not Specified":
                    master_json["parties"].append(party)
                    
            for key in ["effective_date", "liability_cap", "termination_conditions"]:
                val = result.get(key, "Not Specified")
                if master_json[key] == "Not Specified" and val != "Not Specified":
                    master_json[key] = val

        return _build_response(200, {"status": "success", "extracted_data": master_json})

    except Exception as e:
        print(f"Fatal Execution Exception: {str(e)}")
        return _build_response(500, {"error": str(e)})