import json
import os
import base64
import boto3
import fitz  # PyMuPDF
from llama_cpp import Llama

# ------------------------------------------------------
# COLD START INITIALIZATION
# ------------------------------------------------------
S3_BUCKET = os.environ.get("MODEL_BUCKET", "forge-legal-slm-artifacts-c547855a")
MODEL_KEY = "models/base/legal_slm_custom_q3.gguf"
LOCAL_MODEL_PATH = "/tmp/model.gguf"

s3_client = boto3.client('s3')

print("Initializing Serverless Inference Engine...")

if not os.path.exists(LOCAL_MODEL_PATH):
    print(f"Downloading model from s3://{S3_BUCKET}/{MODEL_KEY}...")
    s3_client.download_file(S3_BUCKET, MODEL_KEY, LOCAL_MODEL_PATH)
    print("Download complete.")

# FIX 1: Enforce explicit n_ctx to overwrite the 1024 baseline limit
N_CTX = 4096
MAX_COMPLETION_TOKENS = 1024
llm = Llama(
    model_path=LOCAL_MODEL_PATH,
    n_ctx=N_CTX,
    n_threads=4,
    verbose=False
)
print("Model loaded into memory successfully.")

# Budget left over for the actual document text after reserving space for
# the completion. Without this, chunks sized purely by page count can
# still overflow n_ctx on dense pages -- this is FIX 3, restored here
# after being dropped in a previous merge.
SYSTEM_PROMPT_TOKEN_BUDGET = 100
MAX_PROMPT_TOKENS = N_CTX - MAX_COMPLETION_TOKENS - SYSTEM_PROMPT_TOKEN_BUDGET

# ------------------------------------------------------
# INFERENCE CONFIGURATION
# ------------------------------------------------------
SYSTEM_PROMPT = "Extract structured legal metadata from text into a valid JSON object containing keys: 'parties' (array), 'effective_date' (string), 'liability_cap' (string), and 'termination_conditions' (string). Respond with raw JSON only."


def _build_response(status_code, body):
    return {
        "statusCode": status_code,
        "headers": {
            "Access-Control-Allow-Origin": "*",
            "Access-Control-Allow-Headers": "Content-Type",
            "Access-Control-Allow-Methods": "OPTIONS,POST",
            "Content-Type": "application/json"
        },
        "body": json.dumps(body) if isinstance(body, dict) else body
    }


# FIX 2: Correct structure to match target instruction format without double BOS tags
def build_prompt(text_chunk: str) -> str:
    return (
        "<|start_header_id|>system<|end_header_id|>\n\n"
        f"{SYSTEM_PROMPT}<|eot_id|>"
        "<|start_header_id|>user<|end_header_id|>\n\n"
        f"Document text:\n\"\"\"\n{text_chunk}\n\"\"\"<|eot_id|>"
        "<|start_header_id|>assistant<|end_header_id|>\n\n"
    )


# FIX 3 (RESTORED): token-aware chunking, not blind page-count grouping.
# PAGES_PER_CHUNK-based chunking doesn't account for how dense a given
# page's text is -- a few pages of a dense SEC filing can still blow past
# n_ctx even at 4096, which is exactly what caused the original "Requested
# tokens exceed context window" errors.
def chunk_pdf_by_tokens(doc, max_prompt_tokens: int):
    chunks = []
    current_text = ""
    current_tokens = 0

    for i in range(len(doc)):
        page_text = doc.load_page(i).get_text("text") + "\n\n"
        page_token_count = len(llm.tokenize(page_text.encode("utf-8"), add_bos=False))

        # If a single page alone exceeds the budget, it still gets sent as
        # its own chunk (better to try and risk truncation than silently
        # drop content) rather than compounding the overflow with more pages.
        if current_tokens + page_token_count > max_prompt_tokens and current_text:
            chunks.append(current_text.strip())
            current_text = ""
            current_tokens = 0

        current_text += page_text
        current_tokens += page_token_count

    if current_text.strip():
        chunks.append(current_text.strip())

    return chunks


# FIX 4 (RESTORED): robust JSON extraction that tolerates trailing text
# after the JSON object, instead of plain json.loads() which throws
# "Extra data" and discards the WHOLE chunk's result the moment the model
# generates anything at all after the closing brace.
def extract_first_json_object(text: str):
    decoder = json.JSONDecoder()
    text = text.strip()
    start = text.find("{")
    if start == -1:
        raise ValueError("No JSON object found in model output")
    obj, _ = decoder.raw_decode(text[start:])
    return obj


def extract_json_from_chunk(text_chunk: str):
    prompt = build_prompt(text_chunk)
    try:
        # Lower temperature ensures high strictness for mechanical extraction
        response = llm(prompt, max_tokens=MAX_COMPLETION_TOKENS, stop=["<|eot_id|>"], temperature=0.1)
        output_text = response['choices'][0]['text'].strip()

        # Strip out code blocks markdown formatting wraps if generated by the LLM
        cleaned = output_text.replace("```json", "").replace("```", "").strip()
        return extract_first_json_object(cleaned)
    except Exception as e:
        print(f"Error parsing chunk JSON: {e}")
        return {}


def lambda_handler(event, context):
    print(f"REQUEST RECEIVED: {event.get('httpMethod')} {event.get('path')}")

    # 1. Health Check
    if event.get('httpMethod') == 'GET' or event.get('path') == '/health':
        return _build_response(200, {"status": "alive"})

    # 2. CORS Preflight
    if event.get('httpMethod') == 'OPTIONS':
        return _build_response(200, "OK")

    try:
        # 3. Decode payload body bytes
        body = event.get('body', '')
        is_base64 = event.get('isBase64Encoded', False)
        body_bytes = base64.b64decode(body) if is_base64 else body.encode('utf-8')

        # 4. Handle Multipart-Form data encapsulation or raw PDF data cleanly
        pdf_start = body_bytes.find(b'%PDF-')
        if pdf_start == -1:
            return _build_response(400, {"error": "No valid PDF header found."})

        pdf_end = body_bytes.rfind(b'%%EOF')
        if pdf_end != -1:
            pdf_clean_bytes = body_bytes[pdf_start:pdf_end + 5]
        else:
            pdf_clean_bytes = body_bytes[pdf_start:]

        # 5. Process PDF text streams -- token-aware chunking, see FIX 3 above
        doc = fitz.open(stream=pdf_clean_bytes, filetype="pdf")
        chunks = chunk_pdf_by_tokens(doc, MAX_PROMPT_TOKENS)
        print(f"Split document into {len(chunks)} token-aware chunk(s)")

        # 6. Serialized Execution & Aggregate Result Formatting
        chunk_results = [extract_json_from_chunk(c) for c in chunks]
        master_json = {
            "parties": [],
            "effective_date": "Not Specified",
            "liability_cap": "Not Specified",
            "termination_conditions": "Not Specified"
        }

        for result in chunk_results:
            if not isinstance(result, dict):
                continue

            # Map elements cleanly into aggregated structure
            for party in result.get("parties", []):
                if party not in master_json["parties"] and party != "Not Specified":
                    master_json["parties"].append(party)

            for key in ["effective_date", "liability_cap", "termination_conditions"]:
                val = result.get(key, "Not Specified")
                if master_json[key] == "Not Specified" and val != "Not Specified":
                    master_json[key] = val

        return _build_response(200, {"status": "success", "extracted_data": master_json})

    except Exception as e:
        print(f"Fatal Execution Exception: {str(e)}")
        return _build_response(500, {"error": str(e)})